// Mocks generated by Mockito 5.4.4 from annotations
// in wx_reader_book/test/SelfPageBloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wx_reader_book/data_repository/api_service.dart' as _i3;
import 'package:wx_reader_book/data_repository/KeyValueStorage.dart' as _i2;
import 'package:wx_reader_book/data_repository/repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKeyValuesStorage_0 extends _i1.SmartFake
    implements _i2.KeyValuesStorage {
  _FakeKeyValuesStorage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiService_1 extends _i1.SmartFake implements _i3.ApiService {
  _FakeApiService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Repository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepository extends _i1.Mock implements _i4.Repository {
  @override
  _i2.KeyValuesStorage get keyValuesStorage => (super.noSuchMethod(
        Invocation.getter(#keyValuesStorage),
        returnValue: _FakeKeyValuesStorage_0(
          this,
          Invocation.getter(#keyValuesStorage),
        ),
        returnValueForMissingStub: _FakeKeyValuesStorage_0(
          this,
          Invocation.getter(#keyValuesStorage),
        ),
      ) as _i2.KeyValuesStorage);

  @override
  _i3.ApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeApiService_1(
          this,
          Invocation.getter(#apiService),
        ),
        returnValueForMissingStub: _FakeApiService_1(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i3.ApiService);

  @override
  void init() => super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<dynamic> getData(String? path) => (super.noSuchMethod(
        Invocation.method(
          #getData,
          [path],
        ),
        returnValue: _i5.Future<dynamic>.value(),
        returnValueForMissingStub: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
}
